import React,{useEffect,useRef,useState} from 'react';
import {Menu,X} from 'lucide-react';
import Brand from '@/components/obsiline/Brand';
import Magnetic from '@/components/obsiline/Magnetic';
export default function Chrome(){
 const [open,setOpen]=useState(false),[active,setActive]=useState(''),[scrolled,setScrolled]=useState(false);const progress=useRef(null),cursor=useRef(null),dot=useRef(null);
 useEffect(()=>{let frame;let x=-100,y=-100,lx=x,ly=y;const reduce=window.matchMedia('(prefers-reduced-motion:reduce)').matches;const move=e=>{x=e.clientX;y=e.clientY;cursor.current?.classList.toggle('cursor-active',!!e.target.closest('a,button,.service-card,input'));};const draw=()=>{lx+=(x-lx)*.14;ly+=(y-ly)*.14;if(cursor.current)cursor.current.style.transform=`translate3d(${lx}px,${ly}px,0)`;if(dot.current)dot.current.style.transform=`translate3d(${x}px,${y}px,0)`;frame=requestAnimationFrame(draw);};const scroll=()=>{setScrolled(window.scrollY>30);const total=document.documentElement.scrollHeight-innerHeight;progress.current.style.width=`${total>0?scrollY/total*100:0}%`;};const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');if(e.target.id)setActive(e.target.id);}}),{threshold:.15});document.querySelectorAll('[data-reveal], main section[id]').forEach(e=>observer.observe(e));window.addEventListener('scroll',scroll,{passive:true});if(!reduce&&window.matchMedia('(pointer:fine)').matches){window.addEventListener('pointermove',move);draw();}scroll();return()=>{cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener('scroll',scroll);window.removeEventListener('pointermove',move);};},[]);
 useEffect(()=>{document.body.style.overflow=open?'hidden':'';const backgrounds=[document.querySelector('main'),document.querySelector('footer')];backgrounds.forEach(el=>{if(el)el.inert=open;});if(open)document.querySelector('#mobile-nav a')?.focus();const key=e=>{if(e.key==='Escape')setOpen(false);if(open&&e.key==='Tab'){const links=[document.querySelector('.menu-toggle'),...document.querySelectorAll('#mobile-nav a')];const first=links[0],last=links[links.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow='';backgrounds.forEach(el=>{if(el)el.inert=false;});document.removeEventListener('keydown',key);if(open)document.querySelector('.menu-toggle')?.focus();};},[open]);
 return <><a className="skip-link" href="#main">Skip to content</a><div className="scroll-progress" ref={progress}/><div ref={cursor} className="cursor-ring" aria-hidden="true"/><div ref={dot} className="cursor-dot" aria-hidden="true"/><header className={`site-header ${scrolled?'scrolled':''}`}><Brand/><nav aria-label="Main navigation" className="desktop-nav">{['About','Services','Process','Contact'].map(n=><a className={active===n.toLowerCase()?'active':''} key={n} href={`#${n.toLowerCase()}`}>{n}</a>)}</nav><Magnetic gold href="mailto:obsilinestudio@gmail.com?subject=Book%20a%20call">Book a Call</Magnetic><button className="menu-toggle" aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} aria-controls="mobile-nav" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>{open&&<nav id="mobile-nav" className="mobile-nav" aria-label="Mobile navigation">{['About','Services','Process','Contact'].map((n,i)=><a key={n} href={`#${n.toLowerCase()}`} onClick={()=>setOpen(false)}><small>0{i+1}</small>{n}<span>↗</span></a>)}<p>INTELLIGENT SYSTEMS. REAL GROWTH.</p></nav>}</>;
}